It provides a high-performance multidimensional array object.<br>
It contains various features including these important ones:<br>
A powerful N-dimensional array object<br>
Sophisticated (broadcasting) functions<br>
Tools for integrating C/C++ and Fortran code<br>
Useful linear algebra, Fourier transform, and random number capabilities<br>

 NumPy’s main object is the homogeneous multidimensional array.<br>
It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.<br>
In NumPy dimensions are called axes. The number of axes is rank.<br>
NumPy’s array class is called ndarray. It is also known by the alias array.<br>

In [1]:
import numpy as np

# Creating array object

In [2]:
arr = np.array( [[ 1, 2, 3], 
                 [ 4, 2, 5]] ) 

# Printing type of arr object 

In [3]:
print("Array is of type: ", type(arr)) 

Array is of type:  <class 'numpy.ndarray'>


# Printing array dimensions (axes) 


In [12]:
print("No. of dimensions or axes or rank: ", arr.ndim) 


No. of dimensions or axes or rank:  2


# Printing shape of array 

In [13]:
print("Shape of array: ", arr.shape) 


Shape of array:  (2, 3)


# Printing size (total number of elements) of array 

In [14]:
print("Size of array: ", arr.size) 


Size of array:  6


# Printing type of elements in array 

In [15]:
print("Array stores elements of type: ", arr.dtype) 

Array stores elements of type:  int32


# Want to specify array type use dttype

In [16]:
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float') 

In [17]:
a.dtype

dtype('float64')

# Creating array using Tuple

In [18]:
np.array((1,2,3,4))

array([1, 2, 3, 4])

# Creating array with null value and n*n dimension

In [24]:
c = np.zeros((3, 4)) 

In [25]:
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Creating array with constant value and n*n dimension

In [26]:
d = np.full((3, 3), 6)

In [27]:
d

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

# Creating array with constant value and n*n dimension with data type as complex

In [31]:
d = np.full((3, 3), 6.5, dtype = 'complex') 

In [32]:
d

array([[6.5+0.j, 6.5+0.j, 6.5+0.j],
       [6.5+0.j, 6.5+0.j, 6.5+0.j],
       [6.5+0.j, 6.5+0.j, 6.5+0.j]])

In [33]:
d.dtype

dtype('complex128')

# Create an array with random values 


In [36]:
e = np.random.random((2, 2)) 
e

array([[0.89972492, 0.95564082],
       [0.45588121, 0.58374818]])

In [37]:
f = np.arange(0, 30, 5) 
f

array([ 0,  5, 10, 15, 20, 25])

In [39]:
g = np.linspace(0, 5, 20) 
g

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [40]:
arr = np.array([[1, 2, 3, 4], 
                [5, 2, 4, 2], 
                [1, 2, 0, 1]]) 
newarr = arr.reshape(2, 2, 3) 
newarr

array([[[1, 2, 3],
        [4, 5, 2]],

       [[4, 2, 1],
        [2, 0, 1]]])

In [41]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
arr.flatten() 

array([1, 2, 3, 4, 5, 6])

Array Indexing: Knowing the basics of array indexing is important for analysing and manipulating the array object. NumPy offers many ways to do array indexing.<br>
Slicing: Just like lists in python, NumPy arrays can be sliced. As arrays can be multidimensional, you need to specify a slice for each dimension of the array.<br>
Integer array indexing: In this method, lists are passed for indexing for each dimension. One to one mapping of corresponding elements is done to construct a new arbitrary array.<br>
Boolean array indexing: This method is used when we want to pick elements from array which satisfy some condition.<br>

# Slicing
:n =>n row <br>
::n =>random

In [44]:
arr = np.array([[-1, 2, 0, 4], 
                [4, -0.5, 6, 0], 
                [2.6, 0, 7, 8], 
                [3, -7, 4, 2.0]]) 
arr[:2, ::2] 

array([[-1.,  0.],
       [ 4.,  6.]])

# Unary Operator


In [50]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]]) 

Largest Element

In [51]:
arr.max()

9

Larget element on row basic

In [52]:
arr.max(axis=1)

array([3, 6, 9])

Smallest element column basic

In [53]:
arr.min(axis =0)

array([1, 2, 3])

Circulative Sum of each row and column

In [54]:
arr.cumsum(axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]], dtype=int32)

In [55]:
arr.cumsum(axis=0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]], dtype=int32)

# Binary Operation
+, -, %, *

In [56]:
a = np.array([[1, 2], 
            [3, 4]]) 
b = np.array([[4, 3], 
            [2, 1]])

In [57]:
a+b

array([[5, 5],
       [5, 5]])

In [58]:
a-b

array([[-3, -1],
       [ 1,  3]])

In [59]:
a*b

array([[4, 6],
       [6, 4]])

 Matrix Multiplication

In [60]:
a.dot(b)

array([[ 8,  5],
       [20, 13]])

# Universal Function

In [61]:
a = np.array([0, np.pi/2, np.pi]) 
np.sin(a)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [62]:
np.exp(a)

array([ 1.        ,  4.81047738, 23.14069263])

In [63]:
np.sqrt(a)

array([0.        , 1.25331414, 1.77245385])

# Sorting array

In [64]:
a = np.array([[1, 4, 2], 
                 [3, 4, 6], 
              [0, -1, 5]])

In [65]:
 np.sort(a, axis = None)

array([-1,  0,  1,  2,  3,  4,  4,  5,  6])

In [66]:
np.sort(a, axis = 1)

array([[ 1,  2,  4],
       [ 3,  4,  6],
       [-1,  0,  5]])

In [67]:
np.sort(a, axis = 0, kind = 'mergesort')

array([[ 0, -1,  2],
       [ 1,  4,  5],
       [ 3,  4,  6]])

In [78]:
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)] 
values = [('ss', 2009, 8.5), ('Ajay', 2008, 8.7),  
           ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)] 

In [79]:
np.array(values, dtype = dtypes) 

array([(b'ss', 2009, 8.5), (b'Ajay', 2008, 8.7), (b'Pankaj', 2008, 7.9),
       (b'Aakash', 2009, 9. )],
      dtype=[('name', 'S10'), ('grad_year', '<i4'), ('cgpa', '<f8')])

In [80]:
np.sort(arr, order = 'name')

array([(b'', 2009, 8.5), (b'Aakash', 2009, 9. ), (b'Ajay', 2008, 8.7),
       (b'Pankaj', 2008, 7.9)],
      dtype=[('name', 'S10'), ('grad_year', '<i4'), ('cgpa', '<f8')])

In [81]:
np.sort(arr, order = ['grad_year', 'cgpa'])

array([(b'Pankaj', 2008, 7.9), (b'Ajay', 2008, 8.7), (b'', 2009, 8.5),
       (b'Aakash', 2009, 9. )],
      dtype=[('name', 'S10'), ('grad_year', '<i4'), ('cgpa', '<f8')])

# Basic Operation

In [82]:
a = np.array([1, 2, 5, 3]) 
a+1

array([2, 3, 6, 4])

In [83]:
a-1

array([0, 1, 4, 2])

In [84]:
a**2

array([ 1,  4, 25,  9], dtype=int32)

In [90]:
a *= 2
a

array([ 32,  64, 160,  96])

# Tanspose of array

In [92]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [93]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [105]:
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'bool8') 

In [106]:
a.dtype

dtype('bool')